### PR TITLE
Ho 57 frontend displaying a single listing and comments component

### PR DESCRIPTION
**Pull request by tlchambers**
Please pull branch and have a look and review.
npm install needs to be run front end first
- User is a able to post a comment
- Have their name next to the comment
- Time comment created is also next to comment
- Added a toggle to display/ hide comments
- On listings page if there are comments for that listing (single listing) it will display comment(with number of comments)
- fixed comment tests that were failing

### CODE REVIEW

**Review by AndreeaDinculescu — APPROVED** [review]

**Comment by SyntheticDBX** [comment]
So are the names now showing on each comment?

**Comment by tlchambers** [comment]
Yes tested before lunch and after lunch it's working for me, could someone else test it and let me know if it is working for them?

**Review by mantaslv — CHANGES_REQUESTED** [review]
getting this error when trying to comment even when logged in as an org user:

Listing validation failed: organisationId: Path `organisationId` is required.

**Review by mantaslv — CHANGES_REQUESTED** [review]
works on new posts, but not on old posts so good to go i think as long as we delete those old posts

just one small bug otherwise: log out is broken

**Comment by mantaslv** [comment]
also, at the moment if you are not logged in and click on comments the page breaks, either the button shouldnt show or we can still allow not signed in users to view comments just not add

**Comment by tlchambers** [comment]
Yes forgot to mention, it doesn't work on old listing because there is a new property added on listing so comments only work for new listing

**Comment by tlchambers** [comment]
Argh.. yes trying to fix the bugs now

**Pull request closed without merging**
